with seed_rows (name, user_id, is_global, primary_muscle, equipment) as (
  values
    ('Barbell Bench Press', null::uuid, true, 'Chest', 'Barbell'),
    ('Incline Barbell Bench Press', null::uuid, true, 'Chest', 'Barbell'),
    ('Decline Barbell Bench Press', null::uuid, true, 'Chest', 'Barbell'),
    ('Close-Grip Bench Press', null::uuid, true, 'Chest', 'Barbell'),
    ('Paused Barbell Bench Press', null::uuid, true, 'Chest', 'Barbell'),
    ('Tempo Barbell Bench Press', null::uuid, true, 'Chest', 'Barbell'),
    ('Smith Machine Bench Press', null::uuid, true, 'Chest', 'Smith Machine'),
    ('Dumbbell Bench Press', null::uuid, true, 'Chest', 'Dumbbell'),
    ('Incline Dumbbell Bench Press', null::uuid, true, 'Chest', 'Dumbbell'),
    ('Decline Dumbbell Bench Press', null::uuid, true, 'Chest', 'Dumbbell'),
    ('Single-Arm Dumbbell Bench Press', null::uuid, true, 'Chest', 'Dumbbell'),
    ('Dumbbell Fly', null::uuid, true, 'Chest', 'Dumbbell'),
    ('Incline Dumbbell Fly', null::uuid, true, 'Chest', 'Dumbbell'),
    ('Cable Fly', null::uuid, true, 'Chest', 'Cable'),
    ('High-to-Low Cable Fly', null::uuid, true, 'Chest', 'Cable'),
    ('Low-to-High Cable Fly', null::uuid, true, 'Chest', 'Cable'),
    ('Pec Deck', null::uuid, true, 'Chest', 'Machine'),
    ('Push-Up', null::uuid, true, 'Chest', 'Bodyweight'),
    ('Weighted Push-Up', null::uuid, true, 'Chest', 'Bodyweight'),
    ('Deficit Push-Up', null::uuid, true, 'Chest', 'Bodyweight'),
    ('Dips (Chest)', null::uuid, true, 'Chest', 'Bodyweight'),

    ('Deadlift', null::uuid, true, 'Back', 'Barbell'),
    ('Paused Deadlift', null::uuid, true, 'Back', 'Barbell'),
    ('Tempo Deadlift', null::uuid, true, 'Back', 'Barbell'),
    ('Romanian Deadlift', null::uuid, true, 'Back', 'Barbell'),
    ('Stiff-Leg Deadlift', null::uuid, true, 'Back', 'Barbell'),
    ('Single-Leg Romanian Deadlift', null::uuid, true, 'Back', 'Dumbbell'),
    ('Rack Pull', null::uuid, true, 'Back', 'Barbell'),
    ('Snatch-Grip Deadlift', null::uuid, true, 'Back', 'Barbell'),
    ('Pull-Up', null::uuid, true, 'Back', 'Bodyweight'),
    ('Weighted Pull-Up', null::uuid, true, 'Back', 'Bodyweight'),
    ('Neutral-Grip Pull-Up', null::uuid, true, 'Back', 'Bodyweight'),
    ('Chin-Up', null::uuid, true, 'Back', 'Bodyweight'),
    ('Lat Pulldown', null::uuid, true, 'Back', 'Cable'),
    ('Wide-Grip Lat Pulldown', null::uuid, true, 'Back', 'Cable'),
    ('Close-Grip Lat Pulldown', null::uuid, true, 'Back', 'Cable'),
    ('Single-Arm Lat Pulldown', null::uuid, true, 'Back', 'Cable'),
    ('Seated Cable Row', null::uuid, true, 'Back', 'Cable'),
    ('Single-Arm Cable Row', null::uuid, true, 'Back', 'Cable'),
    ('Barbell Row', null::uuid, true, 'Back', 'Barbell'),
    ('Pendlay Row', null::uuid, true, 'Back', 'Barbell'),
    ('Yates Row', null::uuid, true, 'Back', 'Barbell'),
    ('Dumbbell Row', null::uuid, true, 'Back', 'Dumbbell'),
    ('Single-Arm Dumbbell Row', null::uuid, true, 'Back', 'Dumbbell'),
    ('Chest-Supported Row', null::uuid, true, 'Back', 'Machine'),
    ('T-Bar Row', null::uuid, true, 'Back', 'Machine'),
    ('Machine Row', null::uuid, true, 'Back', 'Machine'),
    ('Straight-Arm Pulldown', null::uuid, true, 'Back', 'Cable'),
    ('Face Pull', null::uuid, true, 'Shoulders', 'Cable'),
    ('Back Extension', null::uuid, true, 'Back', 'Bodyweight'),
    ('Reverse Hyperextension', null::uuid, true, 'Back', 'Machine'),

    ('Overhead Press', null::uuid, true, 'Shoulders', 'Barbell'),
    ('Push Press', null::uuid, true, 'Shoulders', 'Barbell'),
    ('Seated Barbell Overhead Press', null::uuid, true, 'Shoulders', 'Barbell'),
    ('Seated Dumbbell Shoulder Press', null::uuid, true, 'Shoulders', 'Dumbbell'),
    ('Arnold Press', null::uuid, true, 'Shoulders', 'Dumbbell'),
    ('Machine Shoulder Press', null::uuid, true, 'Shoulders', 'Machine'),
    ('Smith Machine Shoulder Press', null::uuid, true, 'Shoulders', 'Smith Machine'),
    ('Lateral Raise', null::uuid, true, 'Shoulders', 'Dumbbell'),
    ('Cable Lateral Raise', null::uuid, true, 'Shoulders', 'Cable'),
    ('Leaning Cable Lateral Raise', null::uuid, true, 'Shoulders', 'Cable'),
    ('Front Raise', null::uuid, true, 'Shoulders', 'Dumbbell'),
    ('Plate Front Raise', null::uuid, true, 'Shoulders', 'Plate'),
    ('Rear Delt Fly', null::uuid, true, 'Shoulders', 'Dumbbell'),
    ('Reverse Pec Deck', null::uuid, true, 'Shoulders', 'Machine'),
    ('Cable Rear Delt Fly', null::uuid, true, 'Shoulders', 'Cable'),
    ('Upright Row', null::uuid, true, 'Shoulders', 'Barbell'),

    ('Back Squat', null::uuid, true, 'Legs', 'Barbell'),
    ('High-Bar Back Squat', null::uuid, true, 'Legs', 'Barbell'),
    ('Low-Bar Back Squat', null::uuid, true, 'Legs', 'Barbell'),
    ('Paused Back Squat', null::uuid, true, 'Legs', 'Barbell'),
    ('Tempo Back Squat', null::uuid, true, 'Legs', 'Barbell'),
    ('Front Squat', null::uuid, true, 'Legs', 'Barbell'),
    ('Paused Front Squat', null::uuid, true, 'Legs', 'Barbell'),
    ('Goblet Squat', null::uuid, true, 'Legs', 'Dumbbell'),
    ('Hack Squat', null::uuid, true, 'Legs', 'Machine'),
    ('Smith Machine Squat', null::uuid, true, 'Legs', 'Smith Machine'),
    ('Leg Press', null::uuid, true, 'Legs', 'Machine'),
    ('Single-Leg Press', null::uuid, true, 'Legs', 'Machine'),
    ('Bulgarian Split Squat', null::uuid, true, 'Legs', 'Dumbbell'),
    ('Walking Lunge', null::uuid, true, 'Legs', 'Dumbbell'),
    ('Reverse Lunge', null::uuid, true, 'Legs', 'Dumbbell'),
    ('Step-Up', null::uuid, true, 'Legs', 'Dumbbell'),
    ('Leg Extension', null::uuid, true, 'Legs', 'Machine'),
    ('Seated Leg Curl', null::uuid, true, 'Legs', 'Machine'),
    ('Lying Leg Curl', null::uuid, true, 'Legs', 'Machine'),
    ('Nordic Curl', null::uuid, true, 'Legs', 'Bodyweight'),
    ('Glute Bridge', null::uuid, true, 'Glutes', 'Barbell'),
    ('Hip Thrust', null::uuid, true, 'Glutes', 'Barbell'),
    ('Single-Leg Hip Thrust', null::uuid, true, 'Glutes', 'Bodyweight'),
    ('Cable Kickback', null::uuid, true, 'Glutes', 'Cable'),
    ('Abductor Machine', null::uuid, true, 'Glutes', 'Machine'),
    ('Adductor Machine', null::uuid, true, 'Legs', 'Machine'),
    ('Calf Raise (Standing)', null::uuid, true, 'Legs', 'Machine'),
    ('Calf Raise (Seated)', null::uuid, true, 'Legs', 'Machine'),
    ('Donkey Calf Raise', null::uuid, true, 'Legs', 'Machine'),

    ('Barbell Curl', null::uuid, true, 'Arms', 'Barbell'),
    ('EZ-Bar Curl', null::uuid, true, 'Arms', 'Barbell'),
    ('Cable Curl', null::uuid, true, 'Arms', 'Cable'),
    ('Dumbbell Curl', null::uuid, true, 'Arms', 'Dumbbell'),
    ('Alternating Dumbbell Curl', null::uuid, true, 'Arms', 'Dumbbell'),
    ('Hammer Curl', null::uuid, true, 'Arms', 'Dumbbell'),
    ('Cross-Body Hammer Curl', null::uuid, true, 'Arms', 'Dumbbell'),
    ('Incline Dumbbell Curl', null::uuid, true, 'Arms', 'Dumbbell'),
    ('Concentration Curl', null::uuid, true, 'Arms', 'Dumbbell'),
    ('Preacher Curl', null::uuid, true, 'Arms', 'Machine'),
    ('Machine Biceps Curl', null::uuid, true, 'Arms', 'Machine'),
    ('Triceps Pushdown', null::uuid, true, 'Arms', 'Cable'),
    ('Rope Pushdown', null::uuid, true, 'Arms', 'Cable'),
    ('Reverse-Grip Pushdown', null::uuid, true, 'Arms', 'Cable'),
    ('Overhead Triceps Extension', null::uuid, true, 'Arms', 'Cable'),
    ('Dumbbell Overhead Triceps Extension', null::uuid, true, 'Arms', 'Dumbbell'),
    ('Skullcrusher', null::uuid, true, 'Arms', 'Barbell'),
    ('Close-Grip Push-Up', null::uuid, true, 'Arms', 'Bodyweight'),
    ('Dips (Triceps)', null::uuid, true, 'Arms', 'Bodyweight'),

    ('Plank', null::uuid, true, 'Core', 'Bodyweight'),
    ('Weighted Plank', null::uuid, true, 'Core', 'Bodyweight'),
    ('Side Plank', null::uuid, true, 'Core', 'Bodyweight'),
    ('Hanging Leg Raise', null::uuid, true, 'Core', 'Bodyweight'),
    ('Lying Leg Raise', null::uuid, true, 'Core', 'Bodyweight'),
    ('Cable Crunch', null::uuid, true, 'Core', 'Cable'),
    ('Machine Crunch', null::uuid, true, 'Core', 'Machine'),
    ('Ab Wheel Rollout', null::uuid, true, 'Core', 'Bodyweight'),
    ('Russian Twist', null::uuid, true, 'Core', 'Bodyweight'),
    ('Dead Bug', null::uuid, true, 'Core', 'Bodyweight'),
    ('Pallof Press', null::uuid, true, 'Core', 'Cable'),
    ('Hollow Body Hold', null::uuid, true, 'Core', 'Bodyweight'),

    ('Treadmill Run', null::uuid, true, 'Cardio', 'Cardio Machine'),
    ('Incline Walk', null::uuid, true, 'Cardio', 'Cardio Machine'),
    ('Stationary Bike', null::uuid, true, 'Cardio', 'Cardio Machine'),
    ('Rowing Machine', null::uuid, true, 'Cardio', 'Cardio Machine'),
    ('Stair Climber', null::uuid, true, 'Cardio', 'Cardio Machine'),
    ('Jump Rope', null::uuid, true, 'Cardio', 'Bodyweight'),
    ('Air Bike Sprint', null::uuid, true, 'Cardio', 'Cardio Machine'),
    ('Sled Push', null::uuid, true, 'Cardio', 'Sled')
)
insert into public.exercises (name, user_id, is_global, primary_muscle, equipment)
select seed.name, seed.user_id, seed.is_global, seed.primary_muscle, seed.equipment
from seed_rows as seed
where not exists (
  select 1
  from public.exercises as existing
  where existing.user_id is null
    and lower(btrim(existing.name)) = lower(btrim(seed.name))
);
